# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget Package DesktopGL

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Noesis.MonoGame\Noesis.MonoGame.DesktopGL.csproj
    - name: Update version
      run: |
        dotnet tool install -g dotnet-setversion   
        setversion ${{ github.ref_name }} Noesis.MonoGame\Noesis.MonoGame.DesktopGL.csproj
    - name: Build
      run: dotnet build Noesis.MonoGame\Noesis.MonoGame.DesktopGL.csproj -c Release --no-restore
    - name: Pack Nuget package
      run: dotnet pack Noesis.MonoGame\Noesis.MonoGame.DesktopGL.csproj -c Release --no-restore --output .
    - name: Upload to Nuget.org
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGETORG }} --source https://api.nuget.org/v3/index.json
