# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget Package DesktopGL

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Noesis.MonoGame.DesktopGL.sln 
    - name: Build
      run: dotnet build Noesis.MonoGame.DesktopGL.sln -c Release --no-restore
    - name: Pack Nuget package
      run: dotnet pack Noesis.MonoGame.DesktopGL.sln -c Release --no-restore --output
    - name: Upload to Nuget.org
      run: dotnet  nuget push "*.nupkg" --api-key ${{secrets.NUGETORG}} --source https://api.nuget.org/v3/index.json
